# Generated by Django 5.1 on 2024-10-11 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_full_name_order_invoice_order_paid_order_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
