# Generated by Django 5.1 on 2024-10-24 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productreview_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='order',
        ),
    ]
