# Generated by Django 5.1 on 2024-10-28 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_order_invoice_order_paid'),
        ('store', '0007_productreview_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='order',
        ),
        migrations.AddField(
            model_name='productreview',
            name='order_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.orderitem'),
        ),
    ]
